try
{	
	__DEFINE_CONSTANTS__ = 1;	
}
catch(e)
{
	__DEFINE_CONSTANTS__ <- 1;
	
	print("INCLUDE: aOO - Constants")
	
	// TEntity constants
	CLASSTYPE_NONE 		<- 0;
	CLASSTYPE_CAMERRA 	<- 1;
	CLASSTYPE_OBJECT 	<- 2;
	CLASSTYPE_LIGHT		<- 3;
	CLASSTYPE_TRIGGER	<- 4;
	CLASSTYPE_EMITTER	<- 5;
	CLASSTYPE_INSTANCE	<- 6;
	
	// EXECUTE MODE
	TOOLMODE_PROJECT	<- 0;
	TOOLMODE_EDITOR		<- 2;
}